version: '3'

volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  pg_data:

services:
  crossbar:
    build:
      context: cb
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  doorstep:
    build:
      context: ds
      dockerfile: Dockerfile.doorstep
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - crossbar:crossbar

  ckan_worker:
    entrypoint: /usr/local/bin/ckan-paster
    command:
      - --plugin=ckan
      - jobs
      - worker
      - -c
      - /etc/ckan/production.ini
    container_name: ckan_worker
    build:
      context: ck
      dockerfile: Dockerfile.ckan
    links:
      - ckan_db
      - ckan_solr
      - ckan_redis
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@ckan_db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@ckan_db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@ckan_db/datastore
      - CKAN_SOLR_URL=http://ckan_solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://ckan_redis:6379/1
      - CKAN_DATAPUSHER_URL=http://ckan_datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}

    volumes:
      - ckan_config:/etc/ckan
      - ckan_storage:/var/lib/ckan

  ckan:
    container_name: ckan
    links:
      - ckan_db
      - ckan_solr
      - ckan_redis
    build:
      context: ck
      dockerfile: Dockerfile.ckan
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@ckan_db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@ckan_db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@ckan_db/datastore
      - CKAN_SOLR_URL=http://ckan_solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://ckan_redis:6379/1
      - CKAN_DATAPUSHER_URL=http://ckan_datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}

    volumes:
      - ckan_config:/etc/ckan
      - ckan_storage:/var/lib/ckan

  ckan_datapusher:
    container_name: ckan_datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"

  ckan_db:
    container_name: ckan_db
    image: ckan_local_postgresql
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  ckan_solr:
    container_name: ckan_solr
    image: ckan_solr

  ckan_redis:
    container_name: ckan_redis
    image: redis:latest

  capstone_db:
    image: postgres
    volumes:
      - ./storage/db:/data
    environment:
      PGDATA: /data
    env_file:
      - ./capstone/infrastructure/config/secrets/laravel.env

  capstone_phpfpm:
    build:
      context: ./capstone/infrastructure/containers/phpfpm
      dockerfile: Dockerfile.debug
    links:
      - capstone_db:db
      - capstone_redis:redis
      - crossbar:crossbar
    env_file:
      - ./capstone/infrastructure/config/secrets/laravel.env
      - ./capstone/infrastructure/config/secrets/redis.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      LINTOL_CAPSTONE_URL: ws://crossbar:8080/ws
    volumes:
      - ./capstone/storage/oauth-private.key:/var/www/app/storage/oauth-private.key
      - ./capstone/storage/oauth-public.key:/var/www/app/storage/oauth-public.key

  capstone_nginx:
    image: 036345629021.dkr.ecr.eu-west-1.amazonaws.com/lintol:nginx-19068648
    env_file:
      - ./capstone/infrastructure/config/secrets/laravel.env
    ports:
      - "8082:80"
    links:
      - capstone_phpfpm:phpfpm
    environment:
      LARAVEL_ROOT: "/var/www/app"

  capstone_artisan_subscriber:
    image: 036345629021.dkr.ecr.eu-west-1.amazonaws.com/lintol:artisan-19068648
    env_file:
      - ./capstone/infrastructure/config/secrets/laravel.env
      - ./capstone/infrastructure/config/secrets/redis.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    links:
      - capstone_db:db
      - capstone_redis:redis
    command:
      - "ltl:observe"
    volumes:
      - ./capstone/storage/oauth-private.key:/var/www/app/storage/oauth-private.key
      - ./capstone/storage/oauth-public.key:/var/www/app/storage/oauth-public.key

  capstone_artisan_worker:
    image: 036345629021.dkr.ecr.eu-west-1.amazonaws.com/lintol:artisan-19068648
    env_file:
      - ./capstone/infrastructure/config/secrets/laravel.env
      - ./capstone/infrastructure/config/secrets/redis.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    links:
      - capstone_db:db
      - capstone_redis:redis
    command:
      - "queue:work"
    volumes:
      - ./capstone/storage/oauth-private.key:/var/www/app/storage/oauth-private.key
      - ./capstone/storage/oauth-public.key:/var/www/app/storage/oauth-public.key

  capstone_redis:
    image: redis
    env_file:
      - ./capstone/infrastructure/config/secrets/redis.env
