version: '3'

volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  pg_data:

services:
  ckan_worker:
    entrypoint: /usr/local/bin/ckan-paster
    command:
      - --plugin=ckan
      - jobs
      - worker
      - -c
      - /etc/ckan/production.ini
    container_name: ckan_worker
    image: ckan_local
    links:
      - ckan_db
      - ckan_solr
      - ckan_redis
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@ckan_db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@ckan_db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@ckan_db/datastore
      - CKAN_SOLR_URL=http://ckan_solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://ckan_redis:6379/1
      - CKAN_DATAPUSHER_URL=http://ckan_datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}

    volumes:
      - ckan_config:/etc/ckan
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan

  ckan:
    container_name: ckan
    image: ckan_local
    links:
      - ckan_db
      - ckan_solr
      - ckan_redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@ckan_db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@ckan_db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@ckan_db/datastore
      - CKAN_SOLR_URL=http://ckan_solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://ckan_redis:6379/1
      - CKAN_DATAPUSHER_URL=http://ckan_datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}

    volumes:
      - ckan_config:/etc/ckan
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan

  ckan_datapusher:
    container_name: ckan_datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"

  ckan_db:
    container_name: ckan_db
    build:
      context: ckan
      dockerfile: contrib/docker/postgresql/Dockerfile
      args:
        - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  ckan_solr:
    container_name: ckan_solr
    build:
      context: ckan
      dockerfile: contrib/docker/solr/Dockerfile


  ckan_redis:
    container_name: ckan_redis
    image: redis:latest

