version: '3'

services:
  node:
    image: node
    ports:
      - "8081:8080"
    volumes:
      - ./lintol-frontend:/usr/src/app
    working_dir: /usr/src/app
    command:
      - npm
      - run
      - dev
